# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#theme: jekyll-agency
remote_theme: raviriley/agency-jekyll-theme


# url    : "https://mastiffsystems.com" # the base hostname & protocol for your site, e.g. http://example.com
# baseurl: "" # the subpath of your site, e.g. /blog
# destination: _site

url: "https://mastiff-systems343.github.io"
baseurl: "/mastiff-systems"
destination: _site

title      : Mastiff Systems
email      : support@mastiffsystems.com 
description: "Mastiff Systems is a small IT services company in Lincoln, Nebraska."
author     : Mastiff Systems
logo:
  path: assets/img/clients/favicon.ico
  height: 60px 
  width: 120px


locale: "en-US" 

version: v1.2.0

future: true
timezone: America/Chicago 

markdown: kramdown

# Uncomment following line to use Formspree form ID based URL instead of email based URL
# Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
formspree_form_path: "f/mlderqre"

paginate: 6 
paginate_path: "/blog/page:num/" 

permalink: /blog/:title/


navigation:
  - title: Search
    url: /search/

plugins:
  - jekyll-admin
  - jekyll-remote-theme
  - jekyll-paginate

collections:
  portfolio:
  authors:
    output: true
  category:
    output: true
  jobs:
    output: true
    

permalink: /blog/:title/

# OR if you want different permalinks for different collections, use defaults:
permalink: pretty  # or leave this out entirely

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /blog/:title/
  - scope:
      path: ""
      type: authors
    values:
      layout: "author"
  - scope:
      path: ""
      type: category
    values:
      layout: "category"
  - scope:
      path: ""
      type: jobs
    values:
      layout: job
      permalink: /open-jobs/:title/
      
include:
  - commit-history.txt




