app_spec:
  name: mastiff-systems
  region: sgp
  alerts:
    - rule: DEPLOYMENT_FAILED
    - rule: DOMAIN_FAILED
  features:
    - buildpack-stack=ubuntu-22
  ingress:
    rules:
      - component:
          name: mastiff-systems2
        match:
          path:
            prefix: /mastiff-systems2
  services:
    - name: mastiff-systems2
      environment_slug: ruby
      github:
        branch: master
        repo: mastiff-systems343/mastiff-systems
        deploy_on_push: true
      instance_count: 2
      instance_size_slug: apps-s-1vcpu-1gb
      source_dir: /
      http_port: 8080
      run_command: bundle exec jekyll serve --host 0.0.0.0 --port ${PORT:-8080}
