name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master # Adjust branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add DigitalOcean server to known_hosts
      run: ssh-keyscan -H 164.92.95.206 >> ~/.ssh/known_hosts

    - name: Deploy files to DigitalOcean
      run: |
        rsync -avz --delete ./ root@164.92.95.206:/var/www/mastiff-systems
        


